version: '3.8'

services:
  app:
    build: .
    ports:
      - "7860:7860"
    environment:
      - DOCKER_CONTAINER=1
      - PORT=7860
    volumes:
      - .:/app
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama_data:

networks:
  app-network:
    driver: bridge
